/**
 * Liste des galeries parisiennes récupérée depuis
 * https://www.parisgallerymap.com/galleries_az
 * (Paris Gallery Map — Galleries A→Z)
 */

export const PARIS_GALLERIES_PGMAP: string[] = [
  "193 Gallery",
  "22,48 m²",
  "Martine Aboucaya",
  "Abraham & Wolff",
  "AFIKARIS",
  "Galerie du Jour agnès b.",
  "Air de Paris",
  "Galerie Allen",
  "Andréhn-Schiptjenko",
  "Art : Concept",
  "BACKSLASH",
  "Balice Hertling",
  "Galerie Anne Barrault",
  "Bendana | Pinel Art Contemporain",
  "Galerie Anne-Sarah Bénichou",
  "Galerie Claude Bernard",
  "christian berst art brut",
  "Galerie Bernard Bouche",
  "Bremond Capela",
  "Emanuela Campoli",
  "Galleria Continua",
  "Crèvecoeur",
  "Galerie Chantal Crousel",
  "Danysz",
  "Galerie Valérie Delaunay",
  "Galerie Derouillon",
  "michèle didier",
  "Double V Gallery",
  "Dvir / Paris",
  "galerie frank elbaz",
  "Galerie Éric Dupont",
  "Exo Exo",
  "Imane Farès",
  "Dominique Fiat",
  "Galerie Les filles du calvaire",
  "Gagosian",
  "Galerie Christophe Gaillard",
  "Claire Gastaud",
  "Jean-Kenta Gauthier",
  "Gilles Drouault galerie/multiples",
  "Marian Goodman",
  "Galerie Karsten Greve",
  "Galerie Alain Gutharc",
  "H Gallery",
  "Hauser & Wirth",
  "Galerie Max Hetzler",
  "Galerie Hussenot",
  "Mariane Ibrahim",
  "In Situ - Fabienne Leclerc",
  "JEANNE BUCHER JAEGER",
  "Galerie Bernard Jordan",
  "Jousse Entreprise",
  "Galerie Peter Kilchmann",
  "Galerie La Forest Divonne",
  "Galerie Lahumière",
  "Yvon Lambert",
  "Galerie Arnaud Lefebvre",
  "Galerie Lelong",
  "Loeve&Co",
  "Loevenbruck",
  "Florence Loewy",
  "Maria Lund",
  "MAGNIN-A",
  "Marcelle Alix",
  "MASSIMODECARLO Pièce Unique",
  "Galerie Maubert",
  "Mendes Wood DM",
  "Mennour",
  "Mitterrand",
  "Édouard Montassut",
  "mor charpentier",
  "Galerie Eric Mouchet",
  "Maïa Muller",
  "Galerie Nathalie Obadia",
  "Galerie Odile Ouizeman",
  "Galerie Alberta Pane",
  "Galerie Papillon",
  "PARIS-B",
  "Pavec",
  "Perrotin",
  "The Pill",
  "Galerie Poggi",
  "Galerie Polaris",
  "Galerie Catherine Putman",
  "Almine Rech",
  "Michel Rein",
  "Romero Paprocki",
  "Thaddaeus Ropac",
  "Ruttkowski;68",
  "RX&SLAG",
  "Salle Principale",
  "Galerie Sator",
  "Esther Schipper",
  "By Lara Sedbon",
  "Semiose",
  "Skarstedt",
  "Strouk",
  "Sultana",
  "Suzanne Tarasieve",
  "Templon",
  "Galerie G.-P. & N. Vallois",
  "Galerie Anne de Villepoix",
  "Galerie Jocelyn Wolff",
  "Xippas",
  "David Zwirner",
];

/** URL de la fiche galerie sur Paris Gallery Map */
export function pgmapGalleryUrl(name: string): string {
  const slug = name.replace(/\s+/g, "_");
  return `https://www.parisgallerymap.com/gallery?name=${encodeURIComponent(slug)}`;
}
